#!/usr/bin/env bash
# Installer for the Dew Heater Controller on Raspberry Pi OS.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${PROJECT_ROOT}/.venv"
SERVICE_NAME="dew-heater"
SYSTEMD_UNIT="/etc/systemd/system/${SERVICE_NAME}.service"
ENV_FILE="${PROJECT_ROOT}/.env"
LOG_DIR="${PROJECT_ROOT}/Temp_Humidity_Logs"

if [[ "${EUID}" -ne 0 ]]; then
    echo "Please re-run this installer with sudo or as root." >&2
    exit 1
fi

REQUESTED_USER="${INSTALL_USER:-}"
if [[ -n "${REQUESTED_USER}" ]]; then
    INSTALL_USER="${REQUESTED_USER}"
elif [[ -n "${SUDO_USER:-}" ]]; then
    INSTALL_USER="${SUDO_USER}"
else
    INSTALL_USER="$(logname 2>/dev/null || true)"
fi

if [[ -z "${INSTALL_USER}" ]]; then
    echo "Unable to determine the non-root user that should own the application files." >&2
    echo "Set the INSTALL_USER environment variable and re-run, e.g. INSTALL_USER=pi sudo ./install.sh" >&2
    exit 1
fi

INSTALL_GROUP="$(id -gn "${INSTALL_USER}")"

run_as_user() {
    sudo -u "${INSTALL_USER}" -H -- "$@"
}

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    build-essential

run_as_user python3 -m venv "${VENV_DIR}"
run_as_user "${VENV_DIR}/bin/pip" install --upgrade pip wheel
run_as_user "${VENV_DIR}/bin/pip" install -r "${PROJECT_ROOT}/requirements.txt"

install -d -o "${INSTALL_USER}" -g "${INSTALL_GROUP}" "${LOG_DIR}"

configure_env_file() {
    local reconfigure="yes"
    if [[ -f "${ENV_FILE}" ]]; then
        read -r -p "An existing .env was found. Reconfigure settings? [y/N]: " response
        if [[ ! "${response}" =~ ^[Yy]$ ]]; then
            echo "Keeping existing ${ENV_FILE}."
            reconfigure="no"
        fi
    fi

    if [[ "${reconfigure}" == "no" ]]; then
        return
    fi

    echo
    echo "=== Location settings ==="
    read -r -p "Latitude (decimal degrees, e.g. 42.000000): " AMBIENT_LAT
    read -r -p "Longitude (decimal degrees, e.g. -71.000000): " AMBIENT_LON
    read -r -p "Location name to show on dashboard (e.g. My Backyard Observatory): " AMBIENT_LOCATION_NAME

    echo
    echo "=== GPIO configuration ==="
    read -r -p "BCM pin for DHT11 sensor [16]: " input_dht
    DHT_PIN="${input_dht:-16}"
    read -r -p "BCM pin for relay control [26]: " input_relay
    RELAY_PIN="${input_relay:-26}"

    cat > "${ENV_FILE}" <<EOF
# User-specific environment overrides generated by install.sh.
DEW_DHT_PIN=${DHT_PIN}
DEW_RELAY_PIN=${RELAY_PIN}
AMBIENT_LAT=${AMBIENT_LAT}
AMBIENT_LON=${AMBIENT_LON}
AMBIENT_LOCATION_NAME="${AMBIENT_LOCATION_NAME}"
EOF
    chown "${INSTALL_USER}:${INSTALL_GROUP}" "${ENV_FILE}"
    chmod 640 "${ENV_FILE}"
    echo "Saved personalized settings to ${ENV_FILE}."
}

configure_env_file

cat > "${SYSTEMD_UNIT}" <<EOF
[Unit]
Description=Dew Heater Controller
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=${INSTALL_USER}
Group=${INSTALL_GROUP}
WorkingDirectory=${PROJECT_ROOT}
EnvironmentFile=${ENV_FILE}
ExecStart=${VENV_DIR}/bin/python ${PROJECT_ROOT}/Dew_Heater_Controller.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}.service"
systemctl restart "${SERVICE_NAME}.service"

echo
echo "Installation complete!"
echo "- Service: ${SERVICE_NAME}.service (running)"
echo "- Virtual environment: ${VENV_DIR}"
echo "- Environment overrides: ${ENV_FILE}"
echo
echo "Adjust any GPIO pins or web port in ${ENV_FILE}, then run 'sudo systemctl restart ${SERVICE_NAME}.service'."
